networks:
  springboot-network:
    external: false

services:
  SpringDatabase:
    image: mariadb:lts
    environment:
      - MARIADB_USER=corona
      - MARIADB_PASSWORD=123456
      - MARIADB_DATABASE=bookSystem
      - MARIADB_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - springboot-network

  SpringFrontend:
    image: node:18
    working_dir: /app
    depends_on:
      - springboot
    volumes:
      - ./Proj/front:/app 
    ports:
      - "8080:8080" 
    command: >
      sh -c "npm install && npm run serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - springboot-network
  springboot:
    build:
      context: ./Proj/pro
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - SpringDatabase
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - springboot-network
